main/urls.py
from django.urls import path
from .views import (Universities,UniversityCourses,PqsView,MaterialsView,
                    CreateMaterial,CreatePQ,Adverts,admin_view,approve_advert,
                    approve_advert,approve_pq,approve_material,delete_advert,delete_pq,
                    delete_material,load_courses,HomePage)

app_name = 'scholars'

urlpatterns = [
    path('',HomePage.as_view(),name='homepage'),
    path('universities',Universities.as_view(),name = 'universities'),
    path('<slug>/courses',UniversityCourses.as_view(),name = 'courses'),
    path('materials',MaterialsView.as_view(),name = 'materials'),
    path('<slug>/past-questions',PqsView.as_view(),name = 'pqs'),
    path('add-material',CreateMaterial.as_view(),name = 'add_material'),
    path('add-past-question',CreatePQ.as_view(),name = 'add_pq'),
    path('products/',Adverts.as_view(),name = 'adverts'),
    # Admin 
    path('approve-advert/<slug>',approve_advert,name = 'approve_advert'),
    path('approve-pq/<slug>',approve_pq,name = 'approve_pq'),
    path('approve-material/<slug>',approve_material,name = 'approve_material'),
    path('delete-advert/<slug>',delete_advert,name = 'delete_advert'),
    path('delete-pq/<slug>',delete_pq,name = 'delete_pq'),
    path('delete-material/<slug>',delete_material,name = 'delete_material'),
    path('agba',admin_view,name='agba'),
    # Dropdowns
    path('ajax/load-courses',load_courses,name='ajax_load_courses'),
]

scholars_/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('boss1/', admin.site.urls),
    path('user/',include('users.urls')),
    path('utils/',include('utils.urls')),
    path('',include('main.urls')),
]

users/urls.py
from django.urls import path
from .views import signup,login_view,logout_view,dashboard
from main.views import admin_view

app_name = 'users'
urlpatterns = [
    path('signup',signup,name='signup'),
    path('login',login_view,name='login'),
    path('logout',logout_view,name='logout'),
    path('dashboard',dashboard,name='dashboard'),
    path('boss2',admin_view,name = 'boss2'),
]

main/models.py
from django.db import models
from django.utils.text import slugify
from users.models import Profile


class University(models.Model):
    name = models.CharField(max_length=100,unique=True)
    state = models.CharField(max_length=100)
    abbreviation = models.CharField(max_length=100,null=True,blank=True)
    slug = models.SlugField(blank=True,null=True)
    
    def __str__(self):
        return "{} ------------ {}".format(self.name.upper(),self.abbreviation)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)


    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Universities'


class Course(models.Model):
    university = models.ForeignKey(University,on_delete=models.CASCADE,related_name='courses')
    name = models.CharField(max_length=100,null=True,blank=True)
    abbreviation = models.CharField(max_length=8)
    slug = models.SlugField(blank=True,null=True)
    
    def __str__(self):
        return "{} {}".format(self.name,self.abbreviation)
    
    def save(self,*args,**kwargs):
        slug_name = str(self.university.name+self.name)
        self.slug = slugify(slug_name)
        super().save(*args,**kwargs)

    class Meta:
        ordering = ['name']
    

class Pq(models.Model):
    uploader = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='uploaded_pqs',null=True,blank=True)
    name = models.CharField(max_length=100,unique=True)
    university = models.ForeignKey(University,related_name='pqs',on_delete=models.CASCADE,blank=True,null=True,unique=False)
    course = models.ForeignKey(Course,on_delete=models.CASCADE,blank=True,null=True,unique=False)
    file = models.FileField(upload_to='pqs')
    created_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return "{} file".format(self.name)
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    class Meta:
        ordering = ['name']


class Material(models.Model):
    uploader = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='uploaded_materials',null=True,blank=True)
    name = models.CharField(max_length=100,unique=True)
    file = models.FileField(upload_to='materials')
    created_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    slug = models.SlugField(blank=True,null=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name
        
    class Meta:
        ordering = ['name']

CATEGORY = (
    ("GADGET","GADGET"),
    ("CLOTHING","CLOTHING"),
    ("SHOES","SHOES"),
)

class AdvertProduct(models.Model):
    name = models.CharField(max_length=100,unique=True)
    price = models.FloatField()
    image1 = models.ImageField(upload_to='products')
    image2 = models.ImageField(upload_to='products')
    seller = models.ForeignKey(Profile,related_name='products',on_delete=models.CASCADE)
    category = models.CharField(max_length=12,choices=CATEGORY)
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True,blank=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)
    

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['created_date']

    

users/models.py
from django.db import models
from django.contrib.auth.models import User
# from phonenumber_field.modelfields import PhoneNumberField


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    uploads = models.IntegerField(default=0,null=True,blank=True)
    phone_number = models.CharField(max_length=14)
    is_seller = models.BooleanField(default=False,null=True,blank=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User
# from phonenumber_field.formfields import PhoneNumberField

def validate_password(value):
    if len(value) < 8:
        raise forms.ValidationError(
            ('Password must be up to 8 characters.'),
            params={'value': value},
        )


class SignupForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    phone_number = forms.CharField(max_length=14, required=False,help_text = 'Preferably an active whatsapp number')
    password = forms.CharField(widget=forms.PasswordInput,help_text='Must be up to 8 characters',validators=[validate_password])
    confirm_password = forms.CharField(widget=forms.PasswordInput,validators=[validate_password])

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password1 = cleaned_data.get("password")
        password2 = cleaned_data.get("confirm_password")
        email_query = User.objects.filter(email=email)
        if email_query.exists():
            raise forms.ValidationError("A user with this email already exists!")
        if password1!=password2:
            raise forms.ValidationError("The passwords do not match")

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        username_query = User.objects.filter(username=username)
        if not username_query.exists():
            raise forms.ValidationError("{} does not exist".format(username))

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages

from .forms import SignupForm,LoginForm
from .models import Profile

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            phone_number = form.cleaned_data.get("phone_number")
            password = form.cleaned_data.get("password")

            user = User.objects.create(
                username = username,
                email = email,
            )
            user.set_password(password)
            user.save()
            profile = Profile.objects.create(user=user,phone_number=phone_number)
            profile.save()
            return redirect('users:login')
    else:
        form = SignupForm()
    return render(request,'users/signup.html',{'form':form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect("users:dashboard")
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username,password=password)
                if user:
                    login(request,user)
                    messages.info(request,f'Welcome back, {user.username}')
                    return redirect('users:dashboard')
                messages.error(request,'Wrong credentials')
                return redirect('users:login')
        else:
            form = LoginForm()
        return render(request,'users/login.html',{'form':form})

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('scholars:homepage')

def dashboard(request):
    return render(request,'users/dashboard.html')
    

users/templates/users/admin_dashboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agba</title>
    <link rel="stylesheet" href="{% static 'css/admin_dash.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src="{% static 'js/admin_dash.js' %}"></script>
    
</head>
<body>
    {% include 'navbar.html' %}
    <div class="backdropx"></div>
    <div class="form_backdrop">
        
        <div class="form_container">
            <span class="exit" id='formexit'>
                <span class="exit_icon"></span>
            </span>
            
            <form action="" class="school_form"  method="POST">
                <h1>Add New School</h1>
                {% csrf_token %}
                {{university_form.as_p}}
                <button type="submit" name="university_btn">SUBMIT</button>
            </form>
            
            <form action="" class="material_form" method="POST" enctype="multipart/form-data">
                <h1>Add New Material</h1>
                {% csrf_token %}
                {{material_form.as_p}}
                <button type="submit" name="material_btn">SUBMIT</button>
            </form>
            
            <form action="" class="pq_form" method="POST" enctype="multipart/form-data" data-courses-url="{% url 'scholars:ajax_load_courses' %}">
                <h1>Add New PQ</h1>
                {% csrf_token %}
                {{pq_form.as_p}}
                <button type="submit" name='pq_btn'>SUBMIT</button>
            </form>
            
            <form action="" class="course_form" method="POST">
                <h1>Add New Course</h1>
                {% csrf_token %}
                {{course_form.as_p}}
                <button type="submit" name="course_btn">SUBMIT</button>
            </form>
        </div>
    </div>
    <div class="graph">
        <canvas id="myChart" width="400" height="400"></canvas>
        <script>
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['January', 'February', 'March', 'April', 'May', 'June','July',
                    ,'August','September','October','November','December'],
                    datasets: [{
                        label: 'Number of Uploads',
                        data: [12, 19, 3, 5, 2, 3,2,14,50,10,4,2],
                        backgroundColor: [
                        'rgb(255, 99, 132)',
                        'rgb(54, 162, 235)',
                        'rgb(255, 206, 86)',
                        'rgb(75, 192, 192)',
                        'rgb(153, 102, 255)',
                        'rgb(255, 159, 64)',
                        'rgb(100, 128, 42)',
                        'rgb(3, 128, 42)',
                        'rgb(123, 28, 42)',
                        'rgb(33, 128, 42)',
                        'rgb(203, 128, 42)',
                        'rgb(201, 128, 42)',
                        ],
                        borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(3, 128, 42,1)',
                        'rgba(123, 28, 42,1)',
                        'rgba(33, 128, 42,1)',
                        'rgba(203, 128, 42,1)',
                        'rgba(201, 128, 42,1)',
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    maintainAspectRatio: false,
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            },
                            gridLines: {
                                display: true,
                                color: "rgba(255,255,255,0.2)"
                            }
                        }]
                    }
                }
            });
        </script>
    </div>
    
    <section class="check_section">
        <div class="check_pqs">
            <a href="#"><h3>New PQs</h3></a>
            <a href="#"><h3>{{student_count}} profiles</h3></a>
        </div>
        
        <div class="check_materials">
            <a href="#"><h3>New Materials</h3></a>
            <a href="#" class="mater"><h3>All Materials</h3></a>
        </div>
        
        <div class="check_school_courses">
            <a href="#"><h3>All Schools</h3></a>
        </div>
        
        <div class="check_adverts">
            <a href="#"><h3>New Adverts</h3></a>
        </div>
        
    </section>
    
    <section class="adverts">
        <center><h2>Adverts</h2></center>
        <span class="scroll-left"><span></span></span>
        <div class="adverts_wrapper">
            <div class="advert">
                <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
                <div class="overlay">
                    <span class="title">Title</span>
                    <span class="price">&#8358;5,000.00</span>
                </div>
            </div>
            
            <div class="advert">
                <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
                <div class="overlay">
                    <span class="title">Title</span>
                    <span class="price">&#8358;5,000.00</span>
                </div>
            </div>
            
            <div class="advert">
                <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
                <div class="overlay">
                    <span class="title">Title</span>
                    <span class="price">&#8358;5,000.00</span>
                </div>
            </div>
            <div class="advert">
                <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
                <div class="overlay">
                    <span class="title">Title</span>
                    <span class="price">&#8358;5,000.00</span>
                </div>
            </div>
            <div class="advert">
                <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
                <div class="overlay">
                    <span class="title">Title</span>
                    <span class="price">&#8358;5,000.00</span>
                </div>
            </div>
            <div class="advert">
                <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
                <div class="overlay">
                    <span class="title">Title</span>
                    <span class="price">&#8358;5,000.00</span>
                </div>
            </div>
        </div>
        <span class="scroll-right"><span></span></span>
    </section>
    <section class="add_stuff">
        <a  id='material'><span class="diff">Add Material</span></a>
        <a  id="pq"><span class="diff">Add PQ</span></a>
        <a  id="school"><span class="diff">Add University</span></a>
        <a  id="course"><span class="diff">Add Course</span></a>
    </section>
<div class="all_stuff schools">
    <span class="close_modal">Exit</span>
    <ul class="all_">
        {{universities.count}} Universities
        {% for uni in universities %}
        <li class="all_li">{{uni.name}} ({{uni.abbreviation}})         <span>{{uni.state}}       {{uni.pqs.count}}PQs</span></li>
        {% endfor %}
    </ul>
</div>
<div class="all_stuff materials">
    <span class="close_modal">Exit</span>
    <ul class="all_">
        {% for uni in materials %}
        <li class="all_li">{{uni.name}} ({{uni.uploader.user.username}})       <small>{{uni.created_date}}</small>  <a target="__blank" href="{{uni.file.url}}">view</a></li>
        {% endfor %}
    </ul>
</div>

<div class="all_stuff new_adverts">
    <span class="close_modal">Exit</span>
    <ul class="all_">
        {% for uni in new_adverts %}
        <li class="all_li">{{uni.name}} ({{uni.seller.user.username}})  &#8358;{{uni.price}}  <small>{{uni.created_date}}</small>  <a target="__blank" href="{{uni.image1.url}}">view</a>  <span>
            <a href="{% url 'scholars:approve_advert' uni.slug %}" class="approve">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 22"><defs><style>.cls-1{fill:#fff;}</style></defs><title>Approve</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M30.29.29,11,19.59l-9.29-9.3A1,1,0,0,0,.29,11.71l10,10a1,1,0,0,0,1.42,0l20-20A1,1,0,1,0,30.29.29Z"/></g></g></svg>
                
            </a>
            <a href="{% url 'scholars:delete_advert' uni.slug %}" class="delete">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 449 513"><defs><style>.cls-1{fill:#fff;stroke:#fff;stroke-miterlimit:10;}</style></defs><title>Delete</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M432.5,32.5h-120l-9.4-18.7A24,24,0,0,0,281.6.5H167.3a23.72,23.72,0,0,0-21.4,13.3l-9.4,18.7H16.5a16,16,0,0,0-16,16v32a16,16,0,0,0,16,16h416a16,16,0,0,0,16-16v-32A16,16,0,0,0,432.5,32.5ZM53.7,467.5a48,48,0,0,0,47.9,45H347.4a48,48,0,0,0,47.9-45l21.2-339H32.5Z"/></g></g></svg>  
            </a>
        </span>
    </li>
    {% empty %}
    <li>No new adverts.</li>
    {% endfor %}
</ul>
</div>

<div class="all_stuff new_materials">
    <span class="close_modal">Exit</span>
    <ul class="all_">
        {% for uni in new_materials %}
        <li class="all_li">{{uni.name}} ({{uni.uploader.user.username}})  <small>{{uni.created_date}}</small>  <a target="__blank" href="{{uni.file.url}}">view</a>  <span>
            <a href="{% url 'scholars:approve_material' uni.slug %}" class="approve">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 22"><defs><style>.cls-1{fill:#fff;}</style></defs><title>Approve</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M30.29.29,11,19.59l-9.29-9.3A1,1,0,0,0,.29,11.71l10,10a1,1,0,0,0,1.42,0l20-20A1,1,0,1,0,30.29.29Z"/></g></g></svg>
                
            </a>
            <a href="{% url 'scholars:delete_material' uni.slug %}" class="delete">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 449 513"><defs><style>.cls-1{fill:#fff;stroke:#fff;stroke-miterlimit:10;}</style></defs><title>Delete</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M432.5,32.5h-120l-9.4-18.7A24,24,0,0,0,281.6.5H167.3a23.72,23.72,0,0,0-21.4,13.3l-9.4,18.7H16.5a16,16,0,0,0-16,16v32a16,16,0,0,0,16,16h416a16,16,0,0,0,16-16v-32A16,16,0,0,0,432.5,32.5ZM53.7,467.5a48,48,0,0,0,47.9,45H347.4a48,48,0,0,0,47.9-45l21.2-339H32.5Z"/></g></g></svg>  
            </a>
        </span>
    </li>
    {% empty %}
    <li>No new materials.</li>
    {% endfor %}
</ul>
</div>

<div class="all_stuff new_pqs">
    <span class="close_modal">Exit</span>
    <ul class="all_">
        {% for uni in new_pqs %}
        <li class="all_li">{{uni.name}} ({{uni.uploader.user.username}})  <small>{{uni.created_date}}</small>  <a target="__blank" href="{{uni.file.url}}">view</a>  <span>
            <a href="{% url 'scholars:approve_pq' uni.slug %}" class="approve">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 22"><defs><style>.cls-1{fill:#fff;}</style></defs><title>Approve</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M30.29.29,11,19.59l-9.29-9.3A1,1,0,0,0,.29,11.71l10,10a1,1,0,0,0,1.42,0l20-20A1,1,0,1,0,30.29.29Z"/></g></g></svg>
                
            </a>
            <a href="{% url 'scholars:delete_pq' uni.slug %}" class="delete">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 449 513"><defs><style>.cls-1{fill:#fff;stroke:#fff;stroke-miterlimit:10;}</style></defs><title>Delete</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M432.5,32.5h-120l-9.4-18.7A24,24,0,0,0,281.6.5H167.3a23.72,23.72,0,0,0-21.4,13.3l-9.4,18.7H16.5a16,16,0,0,0-16,16v32a16,16,0,0,0,16,16h416a16,16,0,0,0,16-16v-32A16,16,0,0,0,432.5,32.5ZM53.7,467.5a48,48,0,0,0,47.9,45H347.4a48,48,0,0,0,47.9-45l21.2-339H32.5Z"/></g></g></svg>  
            </a>
        </span>
    </li>
    {% empty %}
    <li>No new Past Questions.</li>
    {% endfor %}
</ul>
</div>

</body>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    $("#id_university").change(function(){
        var url = $("#pqForm").attr("data-courses-url");
        var universityId = $(this).val();
        
        $.ajax({
            url:url,
            data:{
                'university':universityId
            },
            success:function(data){
                $("#id_course").html(data);
            }
        });
    });
</script>
</html>

users/templates/users/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/dash.css' %}">
{% endblock css %}
{% block content %}
{% include 'navbar.html' %}
<div class="dash-wrapper">
    
    
</div>
<style>
    .login_btn_cta{display:none;}
</style>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock css %}
{% block content %}
{% include 'navbar.html' %}
<div class="form-wrapper">
    <h1>Log In</h1> 
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="submit">
            <input type="submit" value="LOGIN">
        </div>
    </form> 
    <div class="lost-password">
        <a href="{% url 'users:signup' %}" class="firs">Don't have an account?</a>
        <a href="#">Forgot Password?</a>
    </div>
</div>
<style>
    .login_btn_cta{display:none;}
</style>
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock css %}
{% block content %}
{% include 'navbar.html' %}
{% if form.errors %}
<center>
    <span class="errors">{{form.non_field_errors}}</span>
</center>
{% endif %}
<div class="form-wrapper">
    <h1>Sign up</h1> 
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="submit">
            <input type="submit" value="SIGN UP">
        </div>
    </form> 
    <div class="lost-password">
        <a href="{% url 'users:login' %}">Already have an account?</a>
    </div>
</div>

{% endblock %}