main/urls.py
from django.urls import path
from .views import (Universities,UniversityCourses,PqsView,MaterialsView,
                    CreateMaterial,CreatePQ,Adverts,admin_view,approve_advert,
                    approve_advert,approve_pq,approve_material,delete_advert,delete_pq,
                    delete_material,load_courses,HomePage)

app_name = 'scholars'

urlpatterns = [
    path('',HomePage.as_view(),name='homepage'),
    path('universities',Universities.as_view(),name = 'universities'),
    path('<slug>/courses',UniversityCourses.as_view(),name = 'courses'),
    path('materials',MaterialsView.as_view(),name = 'materials'),
    path('<slug>/past-questions',PqsView.as_view(),name = 'pqs'),
    path('add-material',CreateMaterial.as_view(),name = 'add_material'),
    path('add-past-question',CreatePQ.as_view(),name = 'add_pq'),
    path('products/',Adverts.as_view(),name = 'adverts'),
    # Admin 
    path('approve-advert/<slug>',approve_advert,name = 'approve_advert'),
    path('approve-pq/<slug>',approve_pq,name = 'approve_pq'),
    path('approve-material/<slug>',approve_material,name = 'approve_material'),
    path('delete-advert/<slug>',delete_advert,name = 'delete_advert'),
    path('delete-pq/<slug>',delete_pq,name = 'delete_pq'),
    path('delete-material/<slug>',delete_material,name = 'delete_material'),
    path('agba',admin_view,name='agba'),
    # Dropdowns
    path('ajax/load-courses',load_courses,name='ajax_load_courses'),
]

scholars_/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('boss1/', admin.site.urls),
    path('user/',include('users.urls')),
    path('utils/',include('utils.urls')),
    path('',include('main.urls')),
]

main/models.py
from django.db import models
from django.utils.text import slugify
from users.models import Profile


class University(models.Model):
    name = models.CharField(max_length=100,unique=True)
    state = models.CharField(max_length=100)
    abbreviation = models.CharField(max_length=100,null=True,blank=True)
    slug = models.SlugField(blank=True,null=True)
    
    def __str__(self):
        return "{} ------------ {}".format(self.name.upper(),self.abbreviation)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)


    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Universities'


class Course(models.Model):
    university = models.ForeignKey(University,on_delete=models.CASCADE,related_name='courses')
    name = models.CharField(max_length=100,null=True,blank=True)
    abbreviation = models.CharField(max_length=8)
    slug = models.SlugField(blank=True,null=True)
    
    def __str__(self):
        return "{} {}".format(self.name,self.abbreviation)
    
    def save(self,*args,**kwargs):
        slug_name = str(self.university.name+self.name)
        self.slug = slugify(slug_name)
        super().save(*args,**kwargs)

    class Meta:
        ordering = ['name']
    

class Pq(models.Model):
    uploader = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='uploaded_pqs',null=True,blank=True)
    name = models.CharField(max_length=100,unique=True)
    university = models.ForeignKey(University,related_name='pqs',on_delete=models.CASCADE,blank=True,null=True,unique=False)
    course = models.ForeignKey(Course,on_delete=models.CASCADE,blank=True,null=True,unique=False)
    file = models.FileField(upload_to='pqs')
    created_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return "{} file".format(self.name)
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    class Meta:
        ordering = ['name']


class Material(models.Model):
    uploader = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='uploaded_materials',null=True,blank=True)
    name = models.CharField(max_length=100,unique=True)
    file = models.FileField(upload_to='materials')
    created_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    slug = models.SlugField(blank=True,null=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self):
        return self.name
        
    class Meta:
        ordering = ['name']

CATEGORY = (
    ("GADGET","GADGET"),
    ("CLOTHING","CLOTHING"),
    ("SHOES","SHOES"),
)

class AdvertProduct(models.Model):
    name = models.CharField(max_length=100,unique=True)
    price = models.FloatField()
    image1 = models.ImageField(upload_to='products')
    image2 = models.ImageField(upload_to='products')
    seller = models.ForeignKey(Profile,related_name='products',on_delete=models.CASCADE)
    category = models.CharField(max_length=12,choices=CATEGORY)
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True,blank=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)
    

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['created_date']

    

main/forms.py
from django import forms
from .models import University,Course,Pq,Material,AdvertProduct


class AdminUniversityForm(forms.ModelForm):
    class Meta:
        fields = ["name","state","abbreviation"]
        model = University


class AdminCourseForm(forms.ModelForm):
    class Meta:
        fields = ["university","name","abbreviation"]
        model = Course

class StudentPQForm(forms.ModelForm):
    class Meta:
        fields = ["name","university","course","file"]
        model = Pq

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["course"].queryset = Course.objects.none()

        if 'university' in self.data:
            try:
                university_id = int(self.data.get('university'))
                self.fields['course'].queryset = Course.objects.filter(university_id=university_id).order_by('name')
            except(ValueError,TypeError):
                pass
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.course_set.order_by('name')

class AdminPQForm(forms.ModelForm):
    class Meta:
        fields = ["name","university","course","file","approved"]
        model = Pq

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ["name","file"]

class AdminMaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ["name","file","approved"]



# Adverts for Products
CATEGORY = (
    ("GADGET","GADGET"),
    ("CLOTHING","CLOTHING"),
    ("SHOES","SHOES"),
)
class AdvertProductForm(forms.ModelForm):
    class Meta:
        fields = ["name","price","image1","image2","category"]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields["category"].choices = CATEGORY

main/views.py
import random
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,CreateView,ListView,DetailView
from django.contrib import messages
from django.db.models import Q
from .forms import AdminCourseForm,AdminMaterialForm,AdminPQForm,AdminUniversityForm,StudentPQForm,MaterialForm
from .models import Material,AdvertProduct,University,Course,Pq
from .mixins import SearchMixin
from users.models import Profile

class HomePage(TemplateView):
    template_name = 'homepage.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        products = AdvertProduct.objects.filter(approved=True)
        # sample = random.sample(set(products),4)
        context['showcase'] = products
        return context


class Universities(SearchMixin,ListView):
    model = University
    template_name = 'main/universities.html'
    paginate_by=20


class UniversityCourses(DetailView):
    model = University
    template_name = 'main/courses.html'
   

def load_courses(request):
    university_id = request.GET.get("university")
    courses = Course.objects.filter(university_id=university_id).order_by('name')
    return render(request,'main/course_dropdown_list.html',{'courses':courses})

class PqsView(DetailView):
    model = Course
    template_name = 'main/pqs.html'



class MaterialsView(SearchMixin,ListView):
    model = Material
    template_name = 'main/materials.html'

   

class CreateMaterial(LoginRequiredMixin, CreateView):
    login_url = 'users:login'
    form_class = MaterialForm
    success_url = reverse_lazy('users:dashboard')
    template_name = 'main/material_form.html'

    def create(self,*args,**kwargs):
        messages.info(request,"Successfully created")


class CreatePQ(LoginRequiredMixin, CreateView):
    login_url = 'users:login'
    form_class = StudentPQForm
    success_url = reverse_lazy('users:dashboard')
    template_name = 'main/pq_form.html'

    def create(self,*args,**kwargs):
        messages.info(request,"Successfully created")


class Adverts(ListView):
    model = AdvertProduct
    template_name = 'main/adverts.html'

    def get_queryset(self,*args,**kwargs):
        queryset = super().get_queryset(*args,**kwargs) 
        return queryset.order_by('price')


# Admin views
@user_passes_test(lambda x:x.is_superuser)
def admin_view(request):
    pq_form = AdminPQForm()
    material_form = AdminMaterialForm()
    university_form = AdminUniversityForm()
    course_form = AdminCourseForm()
    if request.method == "POST":
        if 'pq_btn' in request.POST:
            pq_form = AdminPQForm(request.POST,request.FILES)
            if pq_form.is_valid():
                pq_form.save()
        if 'material_btn' in request.POST:
            material_form = AdminMaterialForm(request.POST,request.FILES)
            if material_form.is_valid():
                material_form.save()
        if 'university_btn' in request.POST:
            university_form = AdminUniversityForm(request.POST)
            if university_form.is_valid():
                university_form.save()
        if 'course_btn' in request.POST:
            course_form = AdminCourseForm(request.POST)
            if course_form.is_valid():
                course_form.save()
    universities = University.objects.all()
    unapproved_adverts = AdvertProduct.objects.filter(approved=False).order_by('-created_date')
    unapproved_materials = Material.objects.filter(approved=False)
    unapproved_pqs = Pq.objects.filter(approved=False)
    materials = Material.objects.filter(approved=True)
    students = Profile.objects.count()
    context = {
        'pq_form':pq_form,
        'material_form':material_form,
        'university_form':university_form,
        'course_form':course_form,
        'universities':universities,
        'materials':materials,
        'student_count':students,
        'new_adverts':unapproved_adverts,
        'new_materials':unapproved_materials,
        'new_pqs':unapproved_pqs,
    }
    return render(request,'users/admin_dashboard.html',context)


# Approving stuff
def approve_advert(request,slug):
    advert = get_object_or_404(AdvertProduct,slug=slug)
    advert.approved = True
    advert.save()
    messages.success(request,"Approved {}".format(advert.name))
    return redirect("users:boss2")

def approve_pq(request,slug):
    pq = get_object_or_404(Pq,slug=slug)
    pq.approved = True
    pq.save()
    messages.success(request,"Approved {}".format(pq.name))
    return redirect("users:boss2")

def approve_material(request,slug):
    material = get_object_or_404(Material,slug=slug)
    material.approved = True
    material.save()
    messages.success(request,"Approved {}".format(material.name))
    return redirect("users:boss2")


# Deleting stuff
def delete_advert(request,slug):
    advert = get_object_or_404(AdvertProduct,slug=slug)
    name = advert.name
    advert.delete()
    messages.success(request,"Deleted {}".format(name))
    return redirect("users:boss2")

def delete_pq(request,slug):
    pq = get_object_or_404(Pq,slug=slug)
    name = pq.name
    pq.delete()
    messages.success(request,"Deleted {}".format(name))
    return redirect("users:boss2")

def delete_material(request,slug):
    material = get_object_or_404(Material,slug=slug)
    name = material.name
    material.delete()
    messages.success(request,"Deleted {}".format(name))
    return redirect("users:boss2")

main/templates/main/adverts.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/adverts.css' %}">
{% endblock css %}
{% block content %}
{% include 'navbar.html' %}
<section class="adverts">
    <center><h2>Shoes</h2></center>
    <span class="scroll-left"><span></span></span>
    <div class="adverts_wrapper">
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
    </div>
    <span class="scroll-right"><span></span></span>
</section>
<section class="adverts">
    <center><h2>Accessories</h2></center>
    <span class="scroll-left2 scroll-left"><span></span></span>
    <div class="adverts_wrapper2 adverts_wrapper">
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
    </div>
    <span class="scroll-right2 scroll-right"><span></span></span>
</section>

<section class="adverts">
    <center><h2>Gadgets</h2></center>
    <span class="scroll-left1 scroll-left"><span></span></span>
    <div class="adverts_wrapper1 adverts_wrapper" >
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
        <div class="advert">
            <img src="{% static 'images/advert (1).jpg' %}" alt="advert">
            <div class="overlay">
                <span class="title">Title</span>
                <span class="price">&#8358;5,000.00</span>
            </div>
        </div>
    </div>
    <span class="scroll-right1 scroll-right"><span></span></span>
</section>
<style>
    nav ul li a:not(.login_btn_cta){
        color:rgb(165, 111, 12);
    }
    nav ul li .children li a{color:#fff;}
    .mobile_big{z-index:15;}
    .backdrop{z-index:10;}
    #nav-icon2{z-index:11;}
</style>
<script src="{% static 'js/admin_dash.js' %}"></script>

{% endblock %}

main/templates/main/course_dropdown_list.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{course.pk}}">{{course.name}}</option>
{% endfor %}

main/templates/main/courses.html
{% extends 'main/materials.html' %}
{% block others %}{% endblock others %}
{% block header %}
{{object.name}}
<span style="display:block;font-size:1.2rem;">Courses</span>
{% endblock header %}
{% block filter %}
{% for course in object.courses.all %}
    <a style="color:#fff;" href="{% url 'scholars:pqs' slug=course.slug %}">
        <li> {{course.abbreviation}} ({{course.name}})</li>
    </a>
{% empty %}
<p>No courses added yet.</p>
{% endfor %}
<style>
    .all_materials{text-align: center;}
    .all_materials ul{margin:auto;}
</style>
<script>
    var searchbox = document.querySelector('body > form > div > div.fletch > input');
    var lists = document.querySelectorAll('body > form > div > div.all_materials > ul > a ');
    searchbox.addEventListener('input',() => {
        var info = searchbox.value.toLowerCase();
        for(let i=0;i<lists.length;i++){
            console.log(lists[i].innerText)
            if(lists[i].innerText.toLowerCase().indexOf(info) > -1){
                lists[i].style.display = 'block';
            }
            else{
                lists[i].style.display = 'none';
            }
    }
    })
  
</script>
{% endblock filter %}

main/templates/main/material_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="SUBMIT">
</form>

main/templates/main/materials.html
{%  extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/materials.css' %}">
{% endblock css %}

{% block content %}
<header>
    {% include 'navbar.html' %}
    <div class="slides">
        <div class="slide fade">
            <img src="images/advert (1).jpg" alt="">
            <div class="text">Caption Text 1</div>
        </div>
        <div class="slide fade">
            <img src="images/advert (2).jpg" alt="">
            <div class="text">Caption Text 2</div>
        </div>
        <div class="slide fade">
            <img src="images/advert (3).jpg" alt="">
            <div class="text">Caption Text 3</div>
        </div>
        <div class="slide fade">
            <img src="images/advert (4).jpg" alt="">
            <div class="text">Caption Text 4</div>
        </div>
    </div>
    <div style="text-align:center;">
        <span class="dot"></span>
        <span class="dot"></span>
        <span class="dot"></span>
    </div>
</header>
<form action="" method="get">
    {% include 'main/search.html' %}
</form>
{% block others %}
<div class="materials_grid">
    <div class="materials_list">
        <h2>Most Downloaded Materials <i class="fa fa-book"></i></h2>
        <ul>
            <li>Lorem ipsum dolor sit amet consectetur.<a href=""><span><i style="color:#fff;"
                            class="fa fa-download"></i></span></a></li>
            <li>Lorem ipsum dolor sit amet consectetur.<a href=""><span><i style="color:#fff;"
                            class="fa fa-download"></i></span></a></li>
            <li>Lorem ipsum dolor sit amet consectetur.<a href=""><span><i style="color:#fff;"
                            class="fa fa-download"></i></span></a></li>
            <li>Lorem ipsum dolor sit amet consectetur.<a href=""><span><i style="color:#fff;"
                            class="fa fa-download"></i></span></a></li>
            <li>Lorem ipsum dolor sit amet consectetur.<a href=""><span><i style="color:#fff;"
                            class="fa fa-download"></i></span></a></li>
            <li>Lorem ipsum dolor sit amet consectetur.<a href=""><span><i style="color:#fff;"
                            class="fa fa-download"></i></span></a></li>

        </ul>
    </div>
    <div class="search_by">
        <h3>Filter Materials:</h3>
        <ul>
            <li><a href="#">Physics</a></li>
            <li><a href="#">Medicine</a></li>
            <li><a href="#">Engineering</a></li>
            <li><a href="#">General Science</a></li>
        </ul>
    </div>
</div>
{% endblock others %}
<div class="all_materials">
    <h1>{% block header %}All Materials {% endblock header %}</h1>
    <ul style="background: rgb(238, 233, 233)">{% block filter %}
        {% for material in object_list %}
        <li>{{material.name}}<a href="{{material.file.url}}"><span><i style="color:#fff;"
                        class="fa fa-download"></i></span></a></li>
        {% empty %}
        <p>No materials added yet.</p>
        {% endfor %}

        {% endblock filter %}
    </ul>
</div>
</div>
<style>
    #nav-icon2 {
        margin-right: 2.5rem;
        /* z-index:5; */

    }

    .backdrop {
        z-index: 2;
    }
</style>
{% include 'footer.html' %}
{% block js %}
<script src="{% static 'js/bubbles.js' %}"></script>
<script src="{% static 'js/scroll.js' %}"></script>
{% endblock js %}

{% endblock content %}

main/templates/main/pq_form.html
<form action="" method="post" id="pqForm" data-courses-url="{% url 'scholars:ajax_load_courses' %}" enctype="multipart/form-data" novalidate> 
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="SUBMIT">
</form>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script>
    $("#id_university").change(function(){
        var url = $("#pqForm").attr("data-courses-url");
        var universityId = $(this).val();
        
        $.ajax({
            url:url,
            data:{
                'university':universityId
            },
            success:function(data){
                $("#id_course").html(data);
            }
        });
    });
</script>

main/templates/main/pqs.html
{% extends 'main/materials.html' %}
{% load static %}
{% block title %}Past Questions{% endblock %}
{% block css %} {{block.super}} {% endblock css%}
{% block others %}{% endblock others %}
{% block header %}{{object.university.abbreviation}} {{object.abbreviation}} {% endblock header %}
{% block filter %}
{% for pq in object.pq_set.all %}
<li>{{pq.name}}<a href="{{pq.file.url}}"><span><i style="color:#fff;" class="fa fa-download"></i></span></a></li>
{% empty %}
<li><p>No Past Question for this course yet.</p></li>
{% endfor %}
{% endblock filter %}

main/templates/main/search.html
<div class="materials_base">
    <div class="fletch">
        <input type="text" class="boxing" placeholder="Search" name="q">
        <div class="icon">
            <button type='submit' style="background:none;border:none;outline:none;"><i style='color:#fff;'
                    class="fa fa-search"></i></button>
        </div>
    </div>

main/templates/main/universities.html
{% extends 'main/materials.html' %}
{% block others %}
<form action="{% url 'scholars:universities' %}" method="get">
    {% include 'main/search.html' %}
</form>
{% endblock others %}
{% block header %}Universities{% endblock header %}
{% block filter %}
{% for uni in object_list %}

    <a style="color:#fff;" href="{% url 'scholars:courses' slug=uni.slug %}">
        <li> {{uni.name|truncatechars:20}} <span style="position:absolute;right:1rem;">{{uni.abbreviation}}</span></li>
    </a>
{% empty %}
<p>No university matches your keywords.</p>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<style>
    .all_materials{text-align: center;}
    .all_materials ul{margin:auto;}
    .all_materials ul li{position:relative;}
</style>
<script>
    var searchbox = document.querySelector('body > form > div > div.fletch > input');
    var lists = document.querySelectorAll('body > form > div > div.all_materials > ul > a ');
    searchbox.addEventListener('input',() => {
        var info = searchbox.value.toLowerCase();
        for(let i=0;i<lists.length;i++){
            console.log(lists[i].innerText)
            if(lists[i].innerText.toLowerCase().indexOf(info) > -1){
                lists[i].style.display = 'block';
            }
            else{
                lists[i].style.display = 'none';
            }
    }
    })
  
</script>

{% endblock filter %}